Repository mbcse/Security_Hacking_Scripts, pull requests merged in 2020-10, with the labels that each got.

#3 Added a Learning resources folder with 1st content.
  Learning Resources/Ehthical hacking book tutorials point.pdf
Labels: good first issue, hacktoberfest-accepted

#25 Added Project Folder
  Projects/.idea/Security_Hacking_Scripts.iml
  Projects/.idea/inspectionProfiles/profiles_settings.xml
  Projects/.idea/modules.xml
  Projects/.idea/vcs.xml
  Projects/.idea/workspace.xml
  Projects/EncryptedChatUsingBasicCypherAlgo/README.md
  Projects/EncryptedChatUsingBasicCypherAlgo/index.html
  Projects/EncryptedChatUsingBasicCypherAlgo/package-lock.json
  Projects/EncryptedChatUsingBasicCypherAlgo/package.json
  Projects/EncryptedChatUsingBasicCypherAlgo/plan.txt
  Projects/EncryptedChatUsingBasicCypherAlgo/public/client.js
  Projects/EncryptedChatUsingBasicCypherAlgo/public/style.css
  Projects/EncryptedChatUsingBasicCypherAlgo/public/wassup.png
  Projects/EncryptedChatUsingBasicCypherAlgo/server.js
Labels: documentation, hacktoberfest-accepted

#26 Improved Readme and shifted files
  Encryption_Algorithms/cieser-cipher-encryption_in_c.c
  Learning Resources/pdfs/Ehthical hacking book tutorials point.pdf
  README.md
Labels: documentation, enhancement, hacktoberfest-accepted
